config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :devices, only: [:index, :show, :new, :create, :destroy] do 
   resources :reservations, only: [:show, :create]
  end
  resources :reservations, only: [:index]
end

app/models/device.rb
class Device < ApplicationRecord
  CATEGORIES = ["speakers", "microphone", "keyboard", "sound-card"]
  belongs_to :user
  has_many :reservations
  validates :name, presence: true
  validates :category, presence: true
  validates :address, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :address, :category ],
    associated_against: {
      user: [ :name ]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @devices = policy_scope(Device)
    @device_name = "All the results for "

    if params[:name].present?
      @devices = @devices.global_search(params[:name])
      @device_name = @device_name + " " + params[:name]
    end

    if params[:category].present?
      @devices = @devices.global_search(params[:category])
      @device_name = @device_name + " " + params[:category]

    end

    if params[:address].present?
      @devices = @devices.near(params[:address], 10)
      @device_name = @device_name + " " + params[:address]
    end

    if @device_name == "All the results for "
      @device_name = "All the devices"
    end

    @markers = @devices.geocoded.map do |device|
      {
        lat: device.latitude,
        lng: device.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { device: device }),
        image_url: helpers.asset_url('logo_red')
      }
    end
  end

  def new
    @device = Device.new
    authorize @device
  end

  def create
    @device = Device.new(device_params)
    @user = current_user
    @device.user = @user
    authorize @device
    if @device.save
      redirect_to device_path(@device)
    else
      render :new
    end
  end

  def show
    @device = Device.find(params[:id])
    authorize @device

    @reservation = Reservation.new
    # authorize @reservation
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy
    authorize @device
    redirect_to devices_path(@device)
  end

  private

  def device_params
    params.require(:device).permit(:name, :category, :photo, :address, :description)
  end
end

app/views/devices/_info_window.html.erb
<%= link_to device_path(device) do %>
  <div class="popup-container">
    <h3><%= device.name %></h3>

    <% if device.photo.attached? %>
      <%= cl_image_tag device.photo.key, height: 120, width: 160, crop: :fill %>
    <% end %>
  </div>
<% end %>

app/views/devices/index.html.erb
  <div class="devindex">
    <div class="devices">
        <div class="cards">
          <h1><%= @device_name %></h1>
            <ul class= "flexy" id="otis">
              <% @devices.each do |device| %>
                <%= link_to device_path(device) do  %>
                  <li>
                    <div class="device-infos">

                      <p class="device_name"><%= device.name %></p>
                      <div class="device_category <%= device.category %>">
                        <i><%= device.category %></i>
                      </div>

                      <p class="device_price"><span><%= device.price %></span>€ / day</p>

                    </div>

                    <div class="device_photo">
                      <% if device.photo.attached? %>
                        <%= cl_image_tag device.photo.key, width: 200, height: 150, class: "img-fit" %>
                      <% else %>
                        <%= cl_image_tag 'kh2rnf8lhwhifjnpdvsu7rwz8enp', width: 200, height: 150, class: "img-fit" %>
                      <% end %>
                    </div>
                  </li>
              <% end %>
            <% end %>
            </ul>
        </div>
    </div>
    <div id="map"
       style="width: 45%; height: 200px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

app/views/devices/new.html.erb
<div class="container">
  <div class="resa-card adding-d">
    <div class="card-flex-add">
      <h1>Add a device</h1>
      <%= simple_form_for(@device) do |f| %>
      <%= f.input :name, label: "Device name :" %>
      <%= f.input :address %>
      <%= f.input :photo, as: :file %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= p "Category :" %>
      <%= f.select :category, ['Choose a category', 'Soundcard', 'Synthesizer', 'Microphone', 'Speakers']%>
      <br>
      <br>
      <div class="btn-card">
      <%= f.submit class: "button-add" %>
      <%= link_to 'Back', devices_path, class: "button-add", id: "back" %>
      </div>
    <% end %>
    </div>
    
  </div>
  
</div>

app/views/devices/show.html.erb
<div class="container">
  <div class="resa-card">
    <div class="card-flex">
    <div class="">
    <% if policy(Device).create? %>
        <h2 id="title"><%= @device.name %></h2>
        <p><%= @device.address %></p>
        <% if @device.description.present? %>
          <h4>Description :</h4>
          <p><%= @device.description.gsub(",", "<br>").html_safe %></p>
        <% end %>
        <hr>
        <% if @device.photo.attached? %>
          <%= cl_image_tag @device.photo.key, height: 300, crop: :fill, class: "img" %>
        <% end %>
      <% end %>
    </div>
      <div class="form">
      <%= simple_form_for([@device, @reservation]) do |f| %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
          <%= f.submit class: "button" %>
      <% end %>

      <%#= form_for :reservation, url: device_reservations_path(@device.id), method: :post do |f| %>
        <%#= f.date_field :start_date, placeholder: "Start Date" , class: "form-date" %>
        <%# <br> %>
        <%#= f.date_field :end_date, placeholder: "End Date", class: "form-date" %>
        <%# <br> %>
        <%#= button_tag( :class => "button") do %>
          <%# Book <%= @device.name ! <i class="far fa-calendar-check"></i> %>
        <%# end %>
      <%# end %>
      </div>
    </div>
  </div>
</div>

<%#= link_to 'Back', devices_path, class: "btn btn-primary" %> |
        <%# if policy(@device).destroy? %>
          <%#= link_to "Remove",
                    device_path(@device),
                    method: :delete,
                    data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
        <%# end %>