config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :devices, only: [:index, :show, :new, :create, :destroy] do 
   resources :reservations, only: [:show, :create]
  end
  resources :reservations, only: [:index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer">
<ul>
<li>contact</li>
<li>about</li>
<li>jo</li>
</ul>
</div> %>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
     We <i class="fas fa-heart"></i> Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="logo-title">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo1.png", class: "logo" %>
    <% end %>
    <h3 id="gear">The Sound of Gear</h3>
  </div>
  <h2 class="rent-to-create">Rent to Create</h2>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link login" %>
        </li>
        <%# <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link login" %>
        <%# </li> %>
        <% if policy(Device).create? %>
          <li>
            <%= link_to "Add a device", new_device_path, class: 'nav-link login' %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Reservations",reservations_path, class: "dropdown-item" %>
        
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link login" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>