config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :devices, only: [:index, :show, :new, :create, :destroy] do 
   resources :reservations, only: [:show, :create]
  end
  resources :reservations, only: [:index]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :device
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    policy_scope(Device)
    
    @reservations = current_user.reservations
    @resa_owner = current_user.devices.map {|device| device.reservations}
  end
  
  def create
    @reservation = Reservation.new(reservation_params)
    authorize @reservation
    @reservation.user = current_user
    @device = Device.find(params[:device_id])
    @reservation.device = @device
    if @reservation.save
      redirect_to device_reservation_path(@device, @reservation)
    else
      render "devices/show"
    end
  end
  def show
    @device = Device.find(params[:device_id])
    @reservation = Reservation.find(params[:id])
    authorize @reservation
  end

private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/views/reservations/index.html.erb
<div class="container-resa">
  <div class="resa-card-dashboard">
    <ul>
      <% @reservations.each do |resa| %>
        <li> <%= p resa.start_date.strftime("%b %d, %Y ") %></li>
        <li> <%= p resa.end_date.strftime("%b %d, %Y ") %></li>
      <% end %>
    </ul>
  </div>

  <div class="resa-card-dashboard mt-0">
    <% @resa_owner.map do |resa| %>
      <ul>
        <% resa.map do |el| %>
          <li><%= el.start_date.strftime("%b %d, %Y ") %></li>
        <%end%>
      </ul>
    <% end %>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container">
<div class="resa-card">
  <div class="card">
    <h1>Reservation Confirmed 🎹</h1>
    <hr>
    <h2 id="pdt">Product: <%= @reservation.device.name %></h2>
    <hr>
    <h4 class="date">Start Date: <%= @reservation.start_date.strftime("%b %d, %Y ") %></h3>
    <hr>
    <h4 class="date">End Date: <%= @reservation.end_date.strftime("%b %d, %Y ") %></h3>
  <%= link_to "Return To Devices", devices_path, class: "btn_back" %>
    
  </div>
</div>
</div>